settings:
#  artifacts-dir: /EasyMiner-Performance-Tests/artifacts/results
  artifacts-dir: /EasyMiner-Performance-Tests/artifacts/%Y-%m-%d_%H-%M-%S.%f

services:
- module: shellexec
  prepare:
#  - head -n1001 ./EasyMiner-Performance-Tests/testing-data/Sacramentorealestatetransactions.csv > ./EasyMiner-Performance-Tests/testing-data/Sacramentorealestatetransactions_1000l.csv
  - command: /EasyMiner-Performance-Tests/EasyMinerTestsPrepare.sh http://easyminer-frontend/easyminercenter/api/users
  post-process:
  - command: /EasyMiner-Performance-Tests/EasyMinerTestsPostProcess.sh

reporting:
#- module: console
#- module: final-stats
- module: prometheus
#- module: blazemeter
#  report-name: Test-EM  # if you will use value 'ask', it will ask it from command line
#  test: Test-EM-reports
#  project: EM

scenarios:
  userDataPreprocessScenario:
#    script: prepared-running-tests/EM-center_datasources_1000l.jmx
    script: prepared-running-tests/EM-short-test.jmx

# Runs items under execution sequential not parallel (default)
modules:
  local:
    sequential: true
  prometheus:
    port: 8008

execution:
- concurrency: 1
#  ramp-up: 30s
#  hold-for: 1m
  iterations: 50
  scenario: userDataPreprocessScenario